AllCops:
  Exclude:
    - 'bin/bundle'
    - 'db/migrate/20240201125603_devise_create_users.rb'
    - 'spec/models/user_spec.rb'
    - 'db/schema.rb'
    - 'spec/requests/users_spec.rb'
    - 'spec/middleware/token_authenticator_spec.rb'
