default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["database_user"] %>
  password: <%= ENV["database_password"] %>
  host: localhost

development:
  <<: *default
  database: garor_development

test:
  <<: *default
  database: garor_test

production:
  <<: *default
  database: garor_production
  username: garor
  password: <%= ENV["GAROR_DATABASE_PASSWORD"] %>
